(function(){
'use strict';
const ROUTE_ADMIN='https://ufnjyidhxuytrmbjzgtu.supabase.co/functions/v1/nwtb-delivery-route-admin';
const BOARD_ADMIN='https://ufnjyidhxuytrmbjzgtu.supabase.co/functions/v1/nwtb-delivery-board-admin';
const $=id=>document.getElementById(id);
function installStyles(){if($('clearRoutesStyles'))return;const s=document.createElement('style');s.id='clearRoutesStyles';s.textContent='.clearRoutesBtn{background:#b42318!important;color:#fff!important;border:1px solid #b42318!important}.clearAvailBtn{background:#fff1f0!important;color:#b42318!important;border:1px solid #fecdca!important}';document.head.appendChild(s)}
function findRefresh(){return Array.from(document.querySelectorAll('button')).find(b=>b.textContent.trim().toUpperCase()==='REFRESH'&&b.closest('.panel,.card,section,div'))}
function installButtons(){if($('clearAllRoutesBtn')&&$('clearAvailableStopsBtn'))return true;const refresh=findRefresh();if(!refresh)return false;if(!$('clearAllRoutesBtn')){const b=document.createElement('button');b.id='clearAllRoutesBtn';b.className='btn clearRoutesBtn';b.textContent='CLEAR ALL ROUTES';b.style.marginLeft='8px';b.onclick=clearAllRoutesWithPin;refresh.insertAdjacentElement('afterend',b)}if(!$('clearAvailableStopsBtn')){const b=document.createElement('button');b.id='clearAvailableStopsBtn';b.className='btn clearAvailBtn';b.textContent='CLEAR AVAILABLE STOPS';b.style.marginLeft='8px';b.onclick=clearAvailableWithConfirm;($('clearAllRoutesBtn')||refresh).insertAdjacentElement('afterend',b)}return true}
window.clearAllRoutesWithPin=async function(){const pin=prompt('Enter route deletion PIN:');if(pin===null)return;if(pin.trim()!=='4201'){alert('Incorrect PIN.');return}if(!confirm('Delete ALL routes? Unfinished stops will return to AVAILABLE.'))return;try{const j=await post(ROUTE_ADMIN,{action:'clear_all_routes',pin:pin.trim()});if(typeof showBanner==='function'&&$('routeMsg'))showBanner('routeMsg',`All routes deleted. ${j.stops_returned||0} unfinished stop(s) returned to AVAILABLE.`,'ok');if(typeof refreshAll==='function')await refreshAll()}catch(e){alert(e.message||'Could not clear routes.')}};
window.clearAvailableWithConfirm=async function(){if(!confirm('Clear every stop currently in AVAILABLE? These stops will be marked CANCELED.'))return;const phrase=prompt('Type CLEAR AVAILABLE STOPS to continue:');if(phrase===null)return;if(phrase.trim()!=='CLEAR AVAILABLE STOPS'){alert('Canceled.');return}try{const j=await post(BOARD_ADMIN,{action:'clear_available',confirmation:'CLEAR AVAILABLE STOPS'});if(typeof showBanner==='function'&&$('routeMsg'))showBanner('routeMsg',`${j.available_cleared||0} AVAILABLE stop(s) cleared.`,'ok');if(typeof refreshAll==='function')await refreshAll()}catch(e){alert(e.message||'Could not clear AVAILABLE stops.')}};
function boot(){installStyles();if(installButtons())return;let n=0;const t=setInterval(()=>{n++;if(installButtons()||n>50)clearInterval(t)},200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
