(function(){
'use strict';
const ROUTE_ADMIN='https://ufnjyidhxuytrmbjzgtu.supabase.co/functions/v1/nwtb-delivery-route-admin';
const BOARD_ADMIN='https://ufnjyidhxuytrmbjzgtu.supabase.co/functions/v1/nwtb-delivery-board-admin';
const $=id=>document.getElementById(id);
function installStyles(){if($('clearRoutesStyles'))return;const s=document.createElement('style');s.id='clearRoutesStyles';s.textContent=`.clearRoutesBtn{background:#b42318!important;color:#fff!important;border:1px solid #b42318!important}.clearAvailBtn{background:#fff1f0!important;color:#b42318!important;border:1px solid #fecdca!important}.clearRoutesModalBack{position:fixed;inset:0;background:rgba(15,23,42,.62);display:none;align-items:center;justify-content:center;z-index:2600;padding:18px}.clearRoutesModalBack.show{display:flex}.clearRoutesModal{width:min(620px,96vw);background:#fff;border-radius:16px;border:1px solid #e4e7ec;box-shadow:0 30px 80px rgba(15,23,42,.3);padding:20px}.clearRoutesModal h2{margin:0;color:#b42318;font-size:20px}.clearRoutesModal p{font-size:12px;line-height:1.5;color:#475467}.clearRoutesWarn{background:#fff1f0;border:1px solid #fecdca;color:#912018;border-radius:10px;padding:12px;font-size:11px;font-weight:700}.clearRoutesModal input{width:100%;box-sizing:border-box;margin-top:10px;padding:10px 11px;border:1px solid #d0d5dd;border-radius:9px;font:inherit}.clearRoutesActions{display:flex;gap:8px;justify-content:flex-end;flex-wrap:wrap;margin-top:14px}.clearRoutesActions button{border:0;border-radius:9px;padding:10px 13px;font-weight:900;cursor:pointer}.clearRoutesCancel{background:#eef1f4;color:#17202a}.clearRoutesConfirm{background:#b42318;color:#fff}.clearRoutesSecondary{background:#fff1f0;color:#b42318;border:1px solid #fecdca!important}.clearRoutesConfirm:disabled,.clearRoutesSecondary:disabled{opacity:.45;cursor:not-allowed}`;document.head.appendChild(s)}
function findRefresh(){return Array.from(document.querySelectorAll('button')).find(b=>b.textContent.trim().toUpperCase()==='REFRESH'&&b.closest('.panel,.card,section,div'))}
function installButtons(){if($('clearAllRoutesBtn')&&$('clearAvailableStopsBtn'))return true;const refresh=findRefresh();if(!refresh)return false;if(!$('clearAllRoutesBtn')){const b=document.createElement('button');b.id='clearAllRoutesBtn';b.className='btn clearRoutesBtn';b.textContent='CLEAR ALL ROUTES';b.style.marginLeft='8px';b.onclick=openClearRoutes;refresh.insertAdjacentElement('afterend',b)}if(!$('clearAvailableStopsBtn')){const b=document.createElement('button');b.id='clearAvailableStopsBtn';b.className='btn clearAvailBtn';b.textContent='CLEAR AVAILABLE STOPS';b.style.marginLeft='8px';b.onclick=openClearAvailable;($('clearAllRoutesBtn')||refresh).insertAdjacentElement('afterend',b)}return true}
function installModal(){if($('clearRoutesModal'))return;const m=document.createElement('div');m.id='clearRoutesModal';m.className='clearRoutesModalBack';m.innerHTML=`<div class="clearRoutesModal"><h2 id="clearRoutesTitle">Clear Dispatch Data?</h2><p id="clearRoutesIntro"></p><div id="clearRoutesWarn" class="clearRoutesWarn"></div><p><b id="clearRoutesPrompt"></b></p><input id="clearRoutesText" autocomplete="off"><div id="clearRoutesMsg" style="margin-top:8px;font-size:11px"></div><div class="clearRoutesActions"><button class="clearRoutesCancel" onclick="closeClearRoutes()">CANCEL</button><button id="clearRoutesSecondary" class="clearRoutesSecondary" style="display:none"></button><button id="clearRoutesConfirm" class="clearRoutesConfirm" disabled></button></div></div>`;m.addEventListener('click',e=>{if(e.target===m)closeClearRoutes()});document.body.appendChild(m)}
let mode='routes';
function configure(){const input=$('clearRoutesText'),confirm=$('clearRoutesConfirm'),secondary=$('clearRoutesSecondary');input.value='';$('clearRoutesMsg').textContent='';secondary.style.display='none';secondary.onclick=null;if(mode==='routes'){$('clearRoutesTitle').textContent='Clear All Routes?';$('clearRoutesIntro').textContent='This removes every route record from the route board.';$('clearRoutesWarn').textContent='Unfinished route stops will be returned to AVAILABLE. Delivered, Not Delivered, and Canceled order outcomes remain intact. If you want an empty working board too, use CLEAR ENTIRE DISPATCH BOARD below.';$('clearRoutesPrompt').textContent='Type CLEAR ALL ROUTES to continue:';input.placeholder='CLEAR ALL ROUTES';confirm.textContent='DELETE ALL ROUTES';secondary.textContent='CLEAR ENTIRE DISPATCH BOARD';secondary.style.display='inline-block';secondary.onclick=()=>{mode='board';configure()}}else if(mode==='available'){$('clearRoutesTitle').textContent='Clear Available Stops?';$('clearRoutesIntro').textContent='This removes every stop currently sitting in AVAILABLE from the working dispatch board.';$('clearRoutesWarn').textContent='The stops are marked CANCELED so they disappear from the board but remain in history. Routes and completed outcomes are not touched.';$('clearRoutesPrompt').textContent='Type CLEAR AVAILABLE STOPS to continue:';input.placeholder='CLEAR AVAILABLE STOPS';confirm.textContent='CLEAR AVAILABLE STOPS'}else{$('clearRoutesTitle').textContent='Clear Entire Dispatch Board?';$('clearRoutesIntro').textContent='This clears all routes and then clears every resulting AVAILABLE stop.';$('clearRoutesWarn').textContent='This is the full reset. Route records are removed, unfinished stops are returned to AVAILABLE, and then all AVAILABLE stops are marked CANCELED. Delivered and Not Delivered outcomes remain in history.';$('clearRoutesPrompt').textContent='Type CLEAR ENTIRE DISPATCH BOARD to continue:';input.placeholder='CLEAR ENTIRE DISPATCH BOARD';confirm.textContent='CLEAR ENTIRE DISPATCH BOARD'}input.oninput=()=>{const needed=mode==='routes'?'CLEAR ALL ROUTES':mode==='available'?'CLEAR AVAILABLE STOPS':'CLEAR ENTIRE DISPATCH BOARD';confirm.disabled=input.value.trim()!==needed};confirm.disabled=true}
window.openClearRoutes=function(){installModal();mode='routes';configure();$('clearRoutesModal').classList.add('show');setTimeout(()=>$('clearRoutesText').focus(),50)};
window.openClearAvailable=function(){installModal();mode='available';configure();$('clearRoutesModal').classList.add('show');setTimeout(()=>$('clearRoutesText').focus(),50)};
window.closeClearRoutes=function(){$('clearRoutesModal')?.classList.remove('show')};
async function clearRoutes(){return post(ROUTE_ADMIN,{action:'clear_all_routes',confirmation:'CLEAR ALL ROUTES'})}
async function clearAvailable(){return post(BOARD_ADMIN,{action:'clear_available',confirmation:'CLEAR AVAILABLE STOPS'})}
window.confirmClearRoutes=async function(){const needed=mode==='routes'?'CLEAR ALL ROUTES':mode==='available'?'CLEAR AVAILABLE STOPS':'CLEAR ENTIRE DISPATCH BOARD';if($('clearRoutesText').value.trim()!==needed)return;const btn=$('clearRoutesConfirm');btn.disabled=true;btn.textContent='CLEARING…';try{if(mode==='routes'){const j=await clearRoutes();$('clearRoutesMsg').textContent=`Done. ${j.routes_deleted} route(s) deleted. ${j.stops_returned} unfinished stop(s) returned to AVAILABLE.`;if(typeof showBanner==='function'&&$('routeMsg'))showBanner('routeMsg',`All routes cleared. ${j.stops_returned} unfinished stops are now AVAILABLE.`,'ok')}else if(mode==='available'){const j=await clearAvailable();$('clearRoutesMsg').textContent=`Done. ${j.available_cleared} AVAILABLE stop(s) removed from the working board.`;if(typeof showBanner==='function'&&$('routeMsg'))showBanner('routeMsg',`${j.available_cleared} AVAILABLE stop(s) cleared.`,'ok')}else{const r=await clearRoutes();const a=await clearAvailable();$('clearRoutesMsg').textContent=`Full reset complete. ${r.routes_deleted} route(s) deleted and ${a.available_cleared} AVAILABLE stop(s) cleared.`;if(typeof showBanner==='function'&&$('routeMsg'))showBanner('routeMsg','Entire dispatch board cleared.','ok')}if(typeof refreshAll==='function')await refreshAll();if(typeof setQueue==='function'){const q=document.querySelector('.filter[data-q="AVAILABLE"]');setQueue('AVAILABLE',q)}setTimeout(closeClearRoutes,1800)}catch(e){$('clearRoutesMsg').textContent=e.message||'Could not clear dispatch data.';btn.disabled=false;btn.textContent=mode==='routes'?'DELETE ALL ROUTES':mode==='available'?'CLEAR AVAILABLE STOPS':'CLEAR ENTIRE DISPATCH BOARD'}};
function boot(){installStyles();installModal();if(installButtons())return;let n=0;const t=setInterval(()=>{n++;if(installButtons()||n>50)clearInterval(t)},200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
