(function(){
'use strict';
const ADMIN='https://ufnjyidhxuytrmbjzgtu.supabase.co/functions/v1/nwtb-delivery-route-admin';
const $=id=>document.getElementById(id);
function installStyles(){if($('clearRoutesStyles'))return;const s=document.createElement('style');s.id='clearRoutesStyles';s.textContent=`.clearRoutesBtn{background:#b42318!important;color:#fff!important;border:1px solid #b42318!important}.clearRoutesBtn:hover{background:#912018!important}.clearRoutesModalBack{position:fixed;inset:0;background:rgba(15,23,42,.62);display:none;align-items:center;justify-content:center;z-index:2600;padding:18px}.clearRoutesModalBack.show{display:flex}.clearRoutesModal{width:min(560px,96vw);background:#fff;border-radius:16px;border:1px solid #e4e7ec;box-shadow:0 30px 80px rgba(15,23,42,.3);padding:20px}.clearRoutesModal h2{margin:0;color:#b42318;font-size:20px}.clearRoutesModal p{font-size:12px;line-height:1.5;color:#475467}.clearRoutesWarn{background:#fff1f0;border:1px solid #fecdca;color:#912018;border-radius:10px;padding:12px;font-size:11px;font-weight:700}.clearRoutesModal input{width:100%;box-sizing:border-box;margin-top:10px;padding:10px 11px;border:1px solid #d0d5dd;border-radius:9px;font:inherit}.clearRoutesActions{display:flex;gap:8px;justify-content:flex-end;margin-top:14px}.clearRoutesActions button{border:0;border-radius:9px;padding:10px 13px;font-weight:900;cursor:pointer}.clearRoutesCancel{background:#eef1f4;color:#17202a}.clearRoutesConfirm{background:#b42318;color:#fff}.clearRoutesConfirm:disabled{opacity:.45;cursor:not-allowed}`;document.head.appendChild(s)}
function findRefresh(){return Array.from(document.querySelectorAll('button')).find(b=>b.textContent.trim().toUpperCase()==='REFRESH'&&b.closest('.panel,.card,section,div'))}
function installButton(){if($('clearAllRoutesBtn'))return true;const refresh=findRefresh();if(!refresh)return false;const b=document.createElement('button');b.id='clearAllRoutesBtn';b.className='btn clearRoutesBtn';b.textContent='CLEAR ALL ROUTES';b.style.marginLeft='8px';b.onclick=openClearRoutes;refresh.insertAdjacentElement('afterend',b);return true}
function installModal(){if($('clearRoutesModal'))return;const m=document.createElement('div');m.id='clearRoutesModal';m.className='clearRoutesModalBack';m.innerHTML=`<div class="clearRoutesModal"><h2>Clear All Routes?</h2><p>This removes every planned, active, completed, and canceled route record from the route board.</p><div class="clearRoutesWarn">Unfinished stops will be returned to AVAILABLE. Delivered, Not Delivered, and Canceled order outcomes will remain intact. Any active driver route will disappear from the Driver Route page after it refreshes.</div><p><b>Type CLEAR ALL ROUTES to continue:</b></p><input id="clearRoutesText" autocomplete="off" placeholder="CLEAR ALL ROUTES"><div id="clearRoutesMsg" style="margin-top:8px;font-size:11px"></div><div class="clearRoutesActions"><button class="clearRoutesCancel" onclick="closeClearRoutes()">CANCEL</button><button id="clearRoutesConfirm" class="clearRoutesConfirm" onclick="confirmClearRoutes()" disabled>DELETE ALL ROUTES</button></div></div>`;m.addEventListener('click',e=>{if(e.target===m)closeClearRoutes()});document.body.appendChild(m);$('clearRoutesText').addEventListener('input',e=>{$('clearRoutesConfirm').disabled=e.target.value.trim()!=='CLEAR ALL ROUTES'})}
window.openClearRoutes=function(){installModal();$('clearRoutesText').value='';$('clearRoutesConfirm').disabled=true;$('clearRoutesMsg').textContent='';$('clearRoutesModal').classList.add('show');setTimeout(()=>$('clearRoutesText').focus(),50)};
window.closeClearRoutes=function(){$('clearRoutesModal')?.classList.remove('show')};
window.confirmClearRoutes=async function(){const input=$('clearRoutesText').value.trim();if(input!=='CLEAR ALL ROUTES')return;const btn=$('clearRoutesConfirm');btn.disabled=true;btn.textContent='CLEARING…';$('clearRoutesMsg').textContent='Removing route assignments and returning unfinished stops to AVAILABLE…';try{const j=await post(ADMIN,{action:'clear_all_routes',confirmation:'CLEAR ALL ROUTES'});$('clearRoutesMsg').textContent=`Done. ${j.routes_deleted} route(s) deleted. ${j.stops_returned} unfinished stop(s) returned to AVAILABLE. ${j.final_orders_preserved} final stop outcome(s) preserved.`;if(typeof refreshAll==='function')await refreshAll();if(typeof setQueue==='function'){const q=document.querySelector('.filter[data-q="AVAILABLE"]');setQueue('AVAILABLE',q)}if(typeof showBanner==='function'&&$('routeMsg'))showBanner('routeMsg',`All routes cleared. ${j.stops_returned} unfinished stops returned to AVAILABLE.`,'ok');setTimeout(closeClearRoutes,1800)}catch(e){$('clearRoutesMsg').textContent=e.message||'Could not clear routes.';btn.disabled=false}finally{btn.textContent='DELETE ALL ROUTES'}};
function boot(){installStyles();installModal();if(installButton())return;let n=0;const t=setInterval(()=>{n++;if(installButton()||n>50)clearInterval(t)},200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
