(function(){
'use strict';
const TRACK_PAUSE='https://ufnjyidhxuytrmbjzgtu.supabase.co/functions/v1/nwtb-delivery-tracking';
const KEY_PAUSE='sb_publishable_EqF-iooqhmngSG5BbzOxfQ_Vnf9Altc';
const tok=()=>localStorage.getItem('nwtb_delivery_token')||'';
async function ppost(payload){const r=await fetch(TRACK_PAUSE,{method:'POST',headers:{'content-type':'application/json','apikey':KEY_PAUSE,'x-nwtb-session':tok()},body:JSON.stringify(payload)}),j=await r.json().catch(()=>({error:'Bad response'}));if(!r.ok)throw Error(j.error||'Request failed');return j}
function styles(){if(document.getElementById('pauseStyles'))return;const s=document.createElement('style');s.id='pauseStyles';s.textContent=`.pauseBox{margin-top:12px;padding:12px;border:1px solid #f6c344;background:#fff8e8;border-radius:10px}.pauseBox.paused{border-color:#f79009;background:#fff4e5}.pauseOverlay{position:fixed;inset:0;background:rgba(15,23,42,.58);display:none;align-items:center;justify-content:center;z-index:5000;padding:16px}.pauseOverlay.show{display:flex}.pauseModal{width:min(520px,96vw);background:#fff;border-radius:16px;padding:18px;box-shadow:0 30px 80px rgba(0,0,0,.3)}.pauseModal textarea{width:100%;min-height:120px;box-sizing:border-box;padding:12px;border:1px solid #bbc4cc;border-radius:9px;font:inherit;resize:vertical}.pauseActions{display:flex;gap:8px;justify-content:flex-end;margin-top:12px}.pauseReason{margin-top:6px;font-size:12px;color:#7a2e0e;font-weight:700}`;document.head.appendChild(s)}
function ensureModal(){styles();if(document.getElementById('pauseOverlay'))return;const x=document.createElement('div');x.id='pauseOverlay';x.className='pauseOverlay';x.innerHTML=`<div class="pauseModal"><h2 style="margin:0 0 6px">PAUSE ROUTE</h2><div class="small" style="margin-bottom:10px">Tell Dispatch why you are pausing. A reason is required and will be sent to Dispatch with your name.</div><textarea id="pauseReasonInput" placeholder="Type the reason for pausing the route..."></textarea><div id="pauseMsg" class="small" style="margin-top:8px"></div><div class="pauseActions"><button class="btn ghost" onclick="closePauseModal()">CANCEL</button><button class="btn amber" onclick="submitPause()">PAUSE ROUTE + NOTIFY DISPATCH</button></div></div>`;x.onclick=e=>{if(e.target===x)closePauseModal()};document.body.appendChild(x)}
window.closePauseModal=function(){document.getElementById('pauseOverlay')?.classList.remove('show')};
window.openPauseModal=function(){ensureModal();const t=document.getElementById('pauseReasonInput');t.value='';document.getElementById('pauseMsg').textContent='';document.getElementById('pauseOverlay').classList.add('show');setTimeout(()=>t.focus(),50)};
window.submitPause=async function(){const reason=(document.getElementById('pauseReasonInput')?.value||'').trim(),msg=document.getElementById('pauseMsg');if(reason.length<3){msg.innerHTML='<span class="warn">A reason is required.</span>';return}try{msg.textContent='Notifying Dispatch…';const j=await ppost({action:'route_pause_driver',route_id:route,driver_employee_number:driver,reason});closePauseModal();if(typeof stopTracking==='function')stopTracking();if(typeof openRoute==='function')await openRoute(route,true);alert('Route paused. Dispatch was notified.')}catch(e){msg.innerHTML='<span class="warn">'+String(e.message||e)+'</span>'}};
window.resumePausedRoute=async function(){if(!confirm('Resume this route now?'))return;try{await ppost({action:'route_resume_driver',route_id:route,driver_employee_number:driver});if(typeof startTracking==='function')startTracking();if(typeof requestWakeLock==='function')requestWakeLock();if(typeof openRoute==='function')await openRoute(route,true)}catch(e){alert(e.message)}};
async function injectPauseControls(id){if(!id||!driver)return;ensureModal();try{const j=await ppost({action:'driver_route_state',route_id:id,driver_employee_number:driver}),r=j.route;const first=document.querySelector('#routes .panel');if(!first)return;let box=document.getElementById('driverPauseBox');if(!box){box=document.createElement('div');box.id='driverPauseBox';first.appendChild(box)}if(r.paused){box.className='pauseBox paused';box.innerHTML=`<b>ROUTE PAUSED</b><div class="pauseReason">${String(r.pause_reason||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}</div><button class="btn green" style="margin-top:9px" onclick="resumePausedRoute()">RESUME ROUTE</button>`}else if(r.status==='ACTIVE'){box.className='pauseBox';box.innerHTML='<b>Need to stop temporarily?</b><div class="small">Pause the route and send Dispatch a required reason.</div><button class="btn amber" style="margin-top:9px" onclick="openPauseModal()">PAUSE ROUTE</button>'}else{box.remove()}}catch(e){console.warn('Pause state check failed',e)}}
const oldOpen=window.openRoute;window.openRoute=async function(id,fromChange=false){const out=await oldOpen(id,fromChange);setTimeout(()=>injectPauseControls(id),80);return out};
styles();ensureModal();
})();