function showStudyPopout(c){if(mode!=='study'||!c?.hasHotspot)return;const pop=$('#studyPartPopout');if(!pop)return;const render=partRender(current,c);if(!render){hideStudyPopout();return;}pop.innerHTML=`<button class="partPopClose" aria-label="Close">×</button><div class="partPopTitle"><span class="num">#${c.number}</span> ${esc(c.name)}</div><div class="partPopStage"><div class="partCard3d"><img src="${render}" alt="${esc(c.name)}"></div></div><div class="partPopHint">Dedicated isolated reference image</div><div class="partPopMeta">${esc(c.excelerator)}</div>`;pop.classList.remove('hidden');pop.querySelector('.partPopClose').onclick=hideStudyPopout;}
function renderHome(){ $('#home').classList.remove('hidden'); $('#workspace').classList.add('hidden'); $('#advanced').classList.add('hidden'); const g=$('#moduleGrid');g.innerHTML='';D.modules.forEach(m=>{let d=document.createElement('div');d.className='moduleCard';d.innerHTML=`<img src="${displayImage(m)}" alt="${esc(m.title)}"><b>${esc(m.title)}</b><div class="muted">${m.components.length} source items</div>`;d.onclick=()=>openModule(m.id,'study');g.appendChild(d)});updateStats();updateTopNav();}
function openModule(id, requestedMode='study'){current=D.modules.find(m=>m.id===id)||D.modules[0];window.NWTB_CURRENT_MODULE=current;selected=null;$('#home').classList.add('hidden');$('#advanced').classList.add('hidden');$('#workspace').classList.remove('hidden');$('#moduleTitle').textContent=current.title;$('#viewerImg').src=displayImage(current);$('#viewerImg').alt=current.title;renderViewer();renderList();renderDetail(null);setMode(requestedMode);updateTopNav();}
function imageBox(){let img=$('#viewerImg'), wrap=$('#viewerWrap'); let r=img.getBoundingClientRect(), wr=wrap.getBoundingClientRect();return {x:r.left-wr.left,y:r.top-wr.top,w:r.width,h:r.height};}
function renderViewer(){let layer=$('#hotspots');layer.innerHTML='';requestAnimationFrame(()=>{const box=imageBox();current.components.filter(c=>c.hasHotspot&&c.x!=null&&c.y!=null).forEach(c=>{let b=document.createElement('button');b.className='hotspot targetOnly';b.dataset.n=c.number;b.textContent='';b.style.left=(box.x+box.w*c.x/100)+'px';b.style.top=(box.y+box.h*c.y/100)+'px';b.title=c.name;b.onclick=e=>{e.stopPropagation();hotspotClick(c)};layer.appendChild(b)});applyModeVisual();});}
function applyModeVisual(){$$('.hotspot').forEach(h=>{const n=+h.dataset.n;let activeNum=null;if(mode==='quiz'&&quiz?.answer)activeNum=quiz.answer.number;else if(mode==='study'&&selected)activeNum=selected.number;h.classList.remove('masked','selectedNumber','targetOnly');h.textContent='';h.style.display='grid';const isActive=activeNum!=null&&n===activeNum;h.style.pointerEvents=(mode==='exam'||mode==='quiz')?'none':'auto';if(mode==='find'||mode==='exam'){h.classList.add('targetOnly');}else if(isActive){h.classList.add('selectedNumber');h.textContent=n;}else{h.classList.add('targetOnly');}});$('#viewerWrap').classList.toggle('exploded',mode==='explode');$('#explodedCloud').classList.toggle('hidden',mode!=='explode');if(mode!=='study')hideStudyPopout();if(mode!=='exam'){closeExamCloseup();clearExamCallout();}else requestAnimationFrame(renderExamCallout);if(mode==='explode') renderExploded();updateTopNav();}
function hotspotClick(c){if(mode==='exam')return;selected=c;$$('.hotspot').forEach(h=>h.classList.toggle('active',+h.dataset.n===c.number));if(mode==='find'&&quiz){answerFind(c)}else{renderDetail(c);if(mode==='study')showStudyPopout(c);}applyModeVisual();}
function renderDetail(c){const box=$('#detail');if(!c){box.innerHTML='<div class="muted">Click a numbered target or choose a component from the list. The PRO version will show an actual source-image close-up for components with hotspot coordinates.</div>';return;}box.innerHTML=`<div class="componentTitle"><span class="num">#${c.number}</span> ${esc(c.name)}</div>${cropHTML(current,c)}<div class="kv"><div class="k">Category</div><div>${esc(c.category)}</div><div class="k">Excelerator</div><div>${esc(c.excelerator)}</div><div class="k">View</div><div>${esc(current.title)}</div></div>${crossViewHTML(c)}${c.name.startsWith('UNRESOLVED')?'<div class="notice">This item is intentionally unresolved because the uploaded answer key leaves it blank. The app does not guess.</div>':''}`;}
function renderList(){let q=($('#search')?.value||'').toLowerCase();let list=$('#componentList');list.innerHTML='';current.components.filter(c=>(c.name+' '+c.excelerator+' '+c.number).toLowerCase().includes(q)).forEach(c=>{let r=document.createElement('div');r.className='row';r.innerHTML=`<div class="num">${c.number}</div><div><b>${esc(c.name)}</b><div class="muted">${esc(c.excelerator)}</div></div>`;r.onclick=()=>{selected=c;renderDetail(c);if(mode==='study')showStudyPopout(c);$$('.hotspot').forEach(h=>h.classList.remove('active'));let h=$(`.hotspot[data-n="${c.number}"]`);if(h){h.classList.add('active');h.scrollIntoView({block:'nearest'})}applyModeVisual();};list.appendChild(r)});}
function setMode(m){mode=m;hideStudyPopout();closeExamCloseup();['study','find','quiz','exam','explode'].forEach(x=>$('#mode-'+x)?.classList.toggle('primary',x===m));$('#quizArea').classList.toggle('hidden',!['find','quiz','exam'].includes(m));const examOnly=m==='exam';$('#search')?.classList.toggle('hidden',examOnly);$('#detail')?.classList.toggle('hidden',examOnly);$('#componentList')?.parentElement?.classList.toggle('hidden',examOnly);if(m==='study'){quiz=null;$('#quizArea').innerHTML='<div class="muted">Study mode: click a target. Dedicated isolated part imagery is shown only when a dedicated reference exists.</div>';}if(m==='quiz')newMCQ(false);if(m==='find')newFind();if(m==='exam')startExam();applyModeVisual();}
function rand(arr){return arr[Math.floor(Math.random()*arr.length)]}
function shuffled(a){return [...a].sort(()=>Math.random()-.5)}
function validComps(){return current.components.filter(c=>!c.name.startsWith('UNRESOLVED'))}
function newMCQ(fromExam){closeExamCloseup();if(fromExam){nextExamQuestion();return;}let pool=validComps();let answer=rand(pool);let distract=shuffled(validComps().filter(c=>c.number!==answer.number)).slice(0,3);quiz={type:'mcq',answer};let choices=shuffled([answer,...distract]);$('#quizArea').innerHTML=`<div class="muted">QUIZ • ${esc(current.title)}</div><div class="question">What is component #${answer.number}?</div>${cropHTML(current,answer,'quizCrop')}<div class="choices">${choices.map(c=>`<button class="btn choice" data-n="${c.number}">${esc(c.name)}</button>`).join('')}</div><div id="feedback" class="feedback"></div><button id="nextQ" class="btn hidden">Next question</button>`;$$('.choice').forEach(b=>b.onclick=()=>answerMCQ(+b.dataset.n,false));applyModeVisual();}
