function buildExamQueue(){const seen=new Set(),all=[];D.modules.forEach(m=>m.components.forEach(c=>{if(!c.hasHotspot||c.x==null||c.y==null||c.name.startsWith('UNRESOLVED'))return;const key=samePartKey(c.name);if(seen.has(key))return;seen.add(key);all.push({module:m,component:c});}));return shuffled(all);}
function nextExamQuestion(){
 closeExamCloseup();clearExamCallout();
 if(examIndex>=examQueue.length){finishExam();return;}
 const item=examQueue[examIndex];current=item.module;window.NWTB_CURRENT_MODULE=current;selected=null;quiz={type:'mcq',answer:item.component};
 $('#moduleTitle').textContent=`EXAM • ${current.title}`;$('#viewerImg').src=displayImage(current);$('#viewerImg').alt=current.title;
 const answer=item.component,distract=shuffled(current.components.filter(c=>!c.name.startsWith('UNRESOLVED')&&samePartKey(c.name)!==samePartKey(answer.name))).slice(0,3),choices=shuffled([answer,...distract]);
 $('#quizArea').innerHTML=`<div class="muted">EXAM • QUESTION ${examIndex+1} OF ${examQueue.length} • ${esc(current.title)}</div><div class="question">Identify component #${answer.number}.</div><div class="examInstruction">Full exam across all truck and engine views. No component repeats. The number is moved away from the component; follow the red arrow to the exact part. Tap the number for a clean, unnumbered inspection view.</div><div class="choices">${choices.map(c=>`<button class="btn choice" data-n="${c.number}">${esc(c.name)}</button>`).join('')}</div><div id="feedback" class="feedback"></div>`;
 $$('.choice').forEach(b=>b.onclick=()=>answerMCQ(+b.dataset.n,true));
 const img=$('#viewerImg');if(img.complete)renderViewer();else img.onload=()=>renderViewer();
}
function record(c,ok){progress.answered++;if(ok)progress.correct++;else{let k=current.id+':'+c.number;progress.missed[k]=(progress.missed[k]||0)+1;}progress.module[current.id]=progress.module[current.id]||{a:0,c:0};progress.module[current.id].a++;if(ok)progress.module[current.id].c++;save();}
function answerMCQ(n,fromExam){if(!quiz)return;let ok=n===quiz.answer.number;record(quiz.answer,ok);let f=$('#feedback');f.innerHTML=ok?'<span class="ok">Correct.</span>':'<span class="bad">Incorrect.</span> Correct answer: '+esc(quiz.answer.name);$$('.choice').forEach(b=>b.disabled=true);if(fromExam){exam.push(ok);examIndex++;setTimeout(nextExamQuestion,700)}else{let next=$('#nextQ');next.classList.remove('hidden');next.onclick=()=>newMCQ(false)}}
function newFind(){let answer=rand(validComps().filter(c=>c.hasHotspot&&c.x!=null&&c.y!=null));quiz={type:'find',answer};$('#quizArea').innerHTML=`<div class="muted">FIND THE PART</div><div class="question">Click the target for: ${esc(answer.name)}</div>${cropHTML(current,answer,'quizCrop')}<div class="muted">The red number labels are masked. Use the source-image close-up above as a visual hint.</div><div id="feedback" class="feedback"></div>`;applyModeVisual();}
function answerFind(c){let ok=c.number===quiz.answer.number;record(quiz.answer,ok);$('#feedback').innerHTML=ok?'<span class="ok">Correct — '+esc(quiz.answer.name)+'</span>':'<span class="bad">Not that target. Correct target was #'+quiz.answer.number+'.</span>';$$('.hotspot').forEach(h=>h.classList.remove('masked'));setTimeout(newFind,900)}
function startExam(){exam=[];examQueue=buildExamQueue();examIndex=0;nextExamQuestion()}
function finishExam(){clearExamCallout();closeExamCloseup();let s=exam.filter(Boolean).length,total=exam.length||examQueue.length;$('#quizArea').innerHTML=`<div class="question">Exam complete</div><div style="font-size:42px;font-weight:900">${s}/${total}</div><div class="muted">${total?Math.round(s/total*100):0}%</div><button id="again" class="btn primary">New exam</button>`;$('#again').onclick=startExam;}
function renderExploded(){let c=$('#explodedCloud');c.innerHTML='';let list=current.components.filter(x=>!x.name.startsWith('UNRESOLVED'));let shown=list.length>28?list.filter((_,i)=>i%2===0):list;shown.forEach((x,i)=>{let el=document.createElement('div');el.className='explodeNode';let side=i%2,left=side?66+((i%5)*3):2+((i%5)*3), top=5+(i%10)*8.7;el.style.left=left+'%';el.style.top=top+'%';el.innerHTML=`<b>#${x.number}</b> ${esc(x.name)}`;el.onclick=()=>renderDetail(x);c.appendChild(el)});}
function showAdvanced(){ $('#home').classList.add('hidden');$('#workspace').classList.add('hidden');$('#advanced').classList.remove('hidden'); renderAdvanced();updateTopNav();}
